<a href="https://colab.research.google.com/github/Akhilesh2804/python/blob/main/DAY_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
j=[4,6,2,8,9]

In [ ]:
numpy array operations

1) numpy         array operations

2) pandas        Data manipulation and analysis

3) matplotib ans Seaborn  Graphical Analysis

4) sklearn Machine learning algorithms and techniques

5) statsmodels  statistical analysis

6) scipy     statstical analysis

In [ ]:
j=[5,7,2,8,4,7]
j

[5, 7, 2, 8, 4, 7]

In [ ]:
np.array(j)

array([5, 7, 2, 8, 4, 7])

In [ ]:
tuple(j)

(5, 7, 2, 8, 4, 7)

In [ ]:
d=np.array(j)
d

array([5, 7, 2, 8, 4, 7])

In [ ]:
type(d)

numpy.ndarray

In [ ]:
d

array([5, 7, 2, 8, 4, 7])

In [ ]:
d.shape

(6,)

In [ ]:
j

[5, 7, 2, 8, 4, 7]

In [ ]:
d.ndim

1

In [ ]:
j

[5, 7, 2, 8, 4, 7]

In [ ]:
d.size

6

In [ ]:
d.reshape(2,3)

array([[5, 7, 2],
       [8, 4, 7]])

In [ ]:
h=d.reshape(2,3)
h

array([[5, 7, 2],
       [8, 4, 7]])

In [ ]:
h.size

6

In [ ]:
h.shape

(2, 3)

In [ ]:
h.ndim

2

In [ ]:
w=d.reshape(3,2)
w

array([[5, 7],
       [2, 8],
       [4, 7]])

In [ ]:
w.shape

(3, 2)

In [ ]:
w.size

6

In [ ]:
w.ndim

2

In [ ]:
d

array([5, 7, 2, 8, 4, 7])

In [ ]:
d.ndim

1

In [ ]:
d.shape

(6,)

In [ ]:
d.size

6

In [ ]:
s=[[4,8,90,12],[56,78,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]]
s

[[4, 8, 90, 12],
 [56, 78, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [ ]:
type(s)

list

In [ ]:
arr1=np.array(s)
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [ ]:
arr1.shape

(5, 4)

In [ ]:
arr1.size

20

In [ ]:
arr1.ndim

2

In [ ]:
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [ ]:
k=arr1.reshape(2,2,5)
k

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 89]],

       [[50, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [ ]:
k.size

20

In [ ]:
k.shape

(2, 2, 5)

In [ ]:
k.ndim

3

In [ ]:
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [ ]:
k

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 89]],

       [[50, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [ ]:
y=arr1.reshape(20,)
y

array([ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55, 90,
       40, 70, 60])

In [ ]:
y.size

20

In [ ]:
y.ndim

1

In [ ]:
y.shape

(20,)

In [ ]:
z=arr1.reshape(20,1)
z

array([[ 4],
       [ 8],
       [90],
       [12],
       [56],
       [78],
       [54],
       [20],
       [67],
       [89],
       [50],
       [49],
       [77],
       [88],
       [22],
       [55],
       [90],
       [40],
       [70],
       [60]])

In [ ]:
z.ndim

2

In [ ]:
z.size

20

In [ ]:
z.shape

(20, 1)

In [ ]:
arr1.shape

(5, 4)

In [ ]:
t=arr1.reshape(2,2,5,1)
t

array([[[[ 4],
         [ 8],
         [90],
         [12],
         [56]],

        [[78],
         [54],
         [20],
         [67],
         [89]]],


       [[[50],
         [49],
         [77],
         [88],
         [22]],

        [[55],
         [90],
         [40],
         [70],
         [60]]]])

In [ ]:
t.ndim

4

In [ ]:
t.size

20

In [ ]:
t.shape

(2, 2, 5, 1)

In [ ]:
a=arr1.reshape(1,2,1,2,5,1)
a

array([[[[[[ 4],
           [ 8],
           [90],
           [12],
           [56]],

          [[78],
           [54],
           [20],
           [67],
           [89]]]],



        [[[[50],
           [49],
           [77],
           [88],
           [22]],

          [[55],
           [90],
           [40],
           [70],
           [60]]]]]])

In [ ]:
range(5,20)

range(5, 20)

In [ ]:
m=[3,4,5,6,7,8]
m

[3, 4, 5, 6, 7, 8]

In [ ]:
list(range(3,101,5))

[3, 8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83, 88, 93, 98]

In [ ]:
list(range(3,13))

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [ ]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [ ]:
tuple(range(5,506,100))

(5, 105, 205, 305, 405, 505)

In [ ]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [ ]:
list(range(-1,-10))

[]

In [ ]:
list(range(-1,-11,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10]

In [ ]:
[2.5,3,3.5,4,4.5]

[2.5, 3, 3.5, 4, 4.5]

In [ ]:
np.arange(2.5,5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
range(5,50,5)

range(5, 50, 5)

In [ ]:
for i in range(5,50,5):
    print('Data',i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [ ]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [ ]:
y=[]
x=[]
for i in range(len(j)):
  if i%2==0:
    x.append(j[i])
  else:
    y.append(j[i])


In [ ]:
for i in j:
  print(i)

5
87
23
46
62
84
80
45
77
33
80


In [1]:
stud_2nd=[18,19,20,20,20,19,18,18,18,20,20]

In [3]:
import numpy as np
np.random.randint(18,21,(300))

array([19, 18, 19, 19, 18, 18, 20, 18, 19, 18, 20, 20, 18, 19, 19, 18, 20,
       20, 20, 20, 20, 19, 18, 20, 20, 19, 18, 18, 20, 20, 18, 18, 20, 18,
       19, 20, 18, 18, 20, 19, 19, 20, 20, 18, 19, 18, 20, 18, 18, 18, 18,
       18, 20, 19, 18, 20, 19, 20, 19, 19, 20, 20, 18, 19, 18, 18, 19, 19,
       18, 18, 19, 19, 19, 20, 20, 18, 19, 20, 20, 20, 19, 19, 18, 19, 19,
       20, 20, 19, 19, 19, 19, 19, 18, 18, 20, 18, 20, 18, 20, 20, 20, 20,
       18, 19, 19, 19, 20, 19, 20, 18, 20, 19, 19, 20, 20, 19, 20, 19, 20,
       18, 18, 20, 18, 20, 19, 19, 18, 18, 19, 19, 19, 19, 20, 18, 20, 18,
       18, 19, 19, 19, 18, 18, 18, 19, 20, 19, 18, 18, 18, 18, 20, 18, 19,
       20, 19, 19, 19, 18, 19, 20, 19, 18, 20, 19, 19, 20, 19, 18, 18, 19,
       20, 19, 19, 18, 19, 20, 20, 20, 20, 19, 19, 20, 20, 19, 18, 18, 19,
       18, 18, 19, 18, 19, 19, 20, 19, 20, 19, 18, 18, 19, 18, 18, 18, 18,
       18, 18, 19, 19, 19, 18, 19, 20, 20, 18, 19, 20, 18, 19, 20, 20, 20,
       19, 18, 19, 20, 20

In [5]:
import numpy as np
tenth_std=np.random.randint(15,18,(1000))
tenth_std

array([16, 17, 17, 16, 16, 17, 16, 16, 15, 17, 16, 15, 16, 16, 17, 16, 15,
       17, 16, 16, 15, 17, 16, 15, 16, 15, 17, 15, 15, 15, 15, 16, 16, 17,
       17, 15, 15, 16, 17, 15, 16, 16, 15, 15, 16, 17, 15, 16, 17, 17, 16,
       15, 17, 15, 17, 17, 16, 15, 16, 15, 17, 17, 17, 16, 16, 16, 17, 15,
       15, 15, 15, 16, 15, 17, 17, 16, 17, 15, 15, 17, 17, 17, 17, 16, 15,
       15, 15, 16, 15, 16, 17, 16, 17, 15, 16, 16, 17, 16, 16, 17, 17, 17,
       17, 17, 15, 16, 17, 16, 17, 17, 15, 17, 15, 17, 15, 17, 16, 17, 16,
       15, 17, 16, 15, 15, 16, 16, 17, 15, 16, 15, 16, 15, 15, 17, 17, 17,
       16, 15, 15, 15, 16, 15, 16, 16, 17, 17, 15, 16, 17, 15, 15, 15, 15,
       17, 17, 17, 16, 16, 16, 16, 15, 15, 17, 16, 15, 16, 16, 15, 17, 15,
       15, 15, 16, 15, 17, 17, 17, 17, 16, 16, 17, 15, 15, 16, 15, 15, 15,
       17, 16, 16, 16, 17, 17, 17, 16, 15, 15, 15, 17, 15, 15, 16, 15, 16,
       15, 16, 15, 16, 16, 15, 15, 17, 15, 16, 16, 15, 15, 16, 17, 15, 17,
       15, 15, 16, 16, 16

In [6]:
arr=np.random.randint(20,99,(6,7))
arr

array([[70, 94, 28, 35, 25, 36, 50],
       [39, 64, 73, 38, 72, 92, 55],
       [93, 88, 43, 54, 37, 95, 48],
       [40, 91, 96, 82, 52, 85, 92],
       [55, 87, 98, 80, 59, 23, 41],
       [75, 76, 95, 48, 75, 85, 27]])

In [7]:
import numpy as np

In [8]:
arr=np.random.randint(20,99,(6,7))
arr

array([[31, 67, 28, 88, 30, 47, 75],
       [37, 37, 96, 75, 24, 90, 83],
       [80, 43, 53, 57, 38, 26, 34],
       [41, 80, 59, 26, 27, 79, 24],
       [55, 85, 78, 48, 74, 86, 53],
       [85, 86, 53, 47, 76, 51, 24]])

In [9]:
arr

array([[31, 67, 28, 88, 30, 47, 75],
       [37, 37, 96, 75, 24, 90, 83],
       [80, 43, 53, 57, 38, 26, 34],
       [41, 80, 59, 26, 27, 79, 24],
       [55, 85, 78, 48, 74, 86, 53],
       [85, 86, 53, 47, 76, 51, 24]])

In [10]:
np.random.seed(234)
arr=np.random.randint(20,99,(6,7))

In [11]:
arr

array([[92, 51, 88, 77, 53, 23, 74],
       [83, 87, 54, 74, 28, 59, 91],
       [52, 79, 84, 46, 91, 43, 23],
       [35, 65, 65, 23, 97, 93, 71],
       [39, 40, 43, 38, 27, 35, 61],
       [23, 93, 60, 93, 75, 43, 98]])

In [12]:
arr[arr<40]

array([23, 28, 23, 35, 23, 39, 38, 27, 35, 23])

In [13]:
arr.size

42

In [38]:
m=[5,20,106,8]
m

[5, 20, 106, 8]

In [39]:
h=[x**2 for x in m]
h

[25, 400, 11236, 64]

In [40]:
g=[m**2 for m in m]
g

[25, 400, 11236, 64]

In [41]:
for i in range(len(m)):
  m[i]=m[i]**2
m

[25, 400, 11236, 64]

In [34]:
b=(5,20,10,6,8)
b

(5, 20, 10, 6, 8)

In [35]:
b=tuple(x+5 for x in b)
b

(10, 25, 15, 11, 13)

In [55]:
k=[55,25,85,75,35,45,95]
k

[55, 25, 85, 75, 35, 45, 95]

In [56]:
a=[x for x in k if x<50]
a

[25, 35, 45]

In [58]:
d=[]
for i in k:
  if i<50:
    d.append(i)
d

[25, 35, 45]

In [59]:
arr=np.random.randint(20,90,10)

In [60]:
arr

array([20, 30, 51, 36, 78, 28, 22, 45, 47, 24])

In [61]:
np.random.seed(5)
arr=np.random.randint(20,90,10)

In [62]:
arr

array([81, 36, 28, 82, 47, 50, 27, 35, 73, 47])

In [63]:
arr+5

array([86, 41, 33, 87, 52, 55, 32, 40, 78, 52])

In [65]:
arr**2

array([6561, 1296,  784, 6724, 2209, 2500,  729, 1225, 5329, 2209])

In [67]:
arr>50

array([ True, False, False,  True, False, False, False, False,  True,
       False])

In [68]:
arr[arr>50]

array([81, 82, 73])

In [69]:
arr[arr>40]

array([81, 82, 47, 50, 73, 47])

In [70]:
arr[arr==40]

array([], dtype=int64)

In [71]:
arr[arr==50]

array([50])