<a href="https://colab.research.google.com/github/Akhilesh2804/python/blob/main/DAY_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
j=[4,6,2,8,9]

In [ ]:
numpy array operations

1) numpy         array operations

2) pandas        Data manipulation and analysis

3) matplotib ans Seaborn  Graphical Analysis

4) sklearn Machine learning algorithms and techniques

5) statsmodels  statistical analysis

6) scipy     statstical analysis

In [3]:
j=[5,7,2,8,4,7]
j

[5, 7, 2, 8, 4, 7]

In [4]:
np.array(j)

array([5, 7, 2, 8, 4, 7])

In [5]:
tuple(j)

(5, 7, 2, 8, 4, 7)

In [6]:
d=np.array(j)
d

array([5, 7, 2, 8, 4, 7])

In [7]:
type(d)

numpy.ndarray

In [8]:
d

array([5, 7, 2, 8, 4, 7])

In [9]:
d.shape

(6,)

In [10]:
j

[5, 7, 2, 8, 4, 7]

In [11]:
d.ndim

1

In [13]:
j

[5, 7, 2, 8, 4, 7]

In [12]:
d.size

6

In [20]:
d.reshape(2,3)

array([[5, 7, 2],
       [8, 4, 7]])

In [21]:
h=d.reshape(2,3)
h

array([[5, 7, 2],
       [8, 4, 7]])

In [22]:
h.size

6

In [23]:
h.shape

(2, 3)

In [25]:
h.ndim

2

In [32]:
w=d.reshape(3,2)
w

array([[5, 7],
       [2, 8],
       [4, 7]])

In [29]:
w.shape

(3, 2)

In [30]:
w.size

6

In [31]:
w.ndim

2

In [24]:
d

array([5, 7, 2, 8, 4, 7])

In [33]:
d.ndim

1

In [34]:
d.shape

(6,)

In [35]:
d.size

6

In [14]:
s=[[4,8,90,12],[56,78,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]]
s

[[4, 8, 90, 12],
 [56, 78, 54, 20],
 [67, 89, 50, 49],
 [77, 88, 22, 55],
 [90, 40, 70, 60]]

In [15]:
type(s)

list

In [16]:
arr1=np.array(s)
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [17]:
arr1.shape

(5, 4)

In [18]:
arr1.size

20

In [19]:
arr1.ndim

2

In [36]:
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [38]:
k=arr1.reshape(2,2,5)
k

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 89]],

       [[50, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [39]:
k.size

20

In [40]:
k.shape

(2, 2, 5)

In [41]:
k.ndim

3

In [42]:
arr1

array([[ 4,  8, 90, 12],
       [56, 78, 54, 20],
       [67, 89, 50, 49],
       [77, 88, 22, 55],
       [90, 40, 70, 60]])

In [43]:
k

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 89]],

       [[50, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [45]:
y=arr1.reshape(20,)
y

array([ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55, 90,
       40, 70, 60])

In [46]:
y.size

20

In [47]:
y.ndim

1

In [48]:
y.shape

(20,)

In [49]:
z=arr1.reshape(20,1)
z

array([[ 4],
       [ 8],
       [90],
       [12],
       [56],
       [78],
       [54],
       [20],
       [67],
       [89],
       [50],
       [49],
       [77],
       [88],
       [22],
       [55],
       [90],
       [40],
       [70],
       [60]])

In [50]:
z.ndim

2

In [51]:
z.size

20

In [52]:
z.shape

(20, 1)

In [54]:
arr1.shape

(5, 4)

In [57]:
t=arr1.reshape(2,2,5,1)
t

array([[[[ 4],
         [ 8],
         [90],
         [12],
         [56]],

        [[78],
         [54],
         [20],
         [67],
         [89]]],


       [[[50],
         [49],
         [77],
         [88],
         [22]],

        [[55],
         [90],
         [40],
         [70],
         [60]]]])

In [58]:
t.ndim

4

In [59]:
t.size

20

In [60]:
t.shape

(2, 2, 5, 1)

In [61]:
a=arr1.reshape(1,2,1,2,5,1)
a

array([[[[[[ 4],
           [ 8],
           [90],
           [12],
           [56]],

          [[78],
           [54],
           [20],
           [67],
           [89]]]],



        [[[[50],
           [49],
           [77],
           [88],
           [22]],

          [[55],
           [90],
           [40],
           [70],
           [60]]]]]])

In [62]:
range(5,20)

range(5, 20)

In [64]:
m=[3,4,5,6,7,8]
m

[3, 4, 5, 6, 7, 8]

In [68]:
list(range(3,101,5))

[3, 8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83, 88, 93, 98]

In [66]:
list(range(3,13))

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [67]:
list(range(3,13,2))

[3, 5, 7, 9, 11]

In [69]:
tuple(range(5,506,100))

(5, 105, 205, 305, 405, 505)

In [70]:
list(range(-10,1))

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0]

In [71]:
list(range(-1,-10))

[]

In [73]:
list(range(-1,-11,-1))

[-1, -2, -3, -4, -5, -6, -7, -8, -9, -10]

In [76]:
[2.5,3,3.5,4,4.5]

[2.5, 3, 3.5, 4, 4.5]

In [78]:
np.arange(2.5,5,0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [79]:
range(5,50,5)

range(5, 50, 5)

In [80]:
for i in range(5,50,5):
    print('Data',i)

Data 5
Data 10
Data 15
Data 20
Data 25
Data 30
Data 35
Data 40
Data 45


In [81]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j

[5, 87, 23, 46, 62, 84, 80, 45, 77, 33, 80]

In [84]:
y=[]
x=[]
for i in range(len(j)):
  if i%2==0:
    x.append(j[i])
  else:
    y.append(j[i])


In [85]:
for i in j:
  print(i)

5
87
23
46
62
84
80
45
77
33
80
